spring.application.name=enrichmentService

server.port=${PORT:8010}

spring.config.import=configserver:${CONFIG_SERVER_URL}

spring.cloud.config.profile=dev

spring.cloud.config.fail-fast=true

eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.client.fetch-registry=true

eureka.client.register-with-eureka=true