spring.application.name=apiGateway

server.port=${PORT:1001}

spring.main.web-application-type=reactive

spring.config.import=configserver:${CONFIG_SERVER_URL}

spring.cloud.config.profile=dev

spring.cloud.config.fail-fast=true

spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

spring.r2dbc.url=r2dbc:mysql://${MYSQLHOST}:${MYSQLPORT}/bankguard_auth

spring.r2dbc.username=${MYSQLUSER}

spring.r2dbc.password=${MYSQLPASSWORD}

jwt.secret=${JWT_SECRET}

jwt.expiration=86400000